#!/usr/bin/env python3
"""
T.G.A.O.T.U. — Workspace Initializer
Creates a complete workspace with instructions, phase distribution,
and agent directive prompts for any new project.

Usage:
    python3 factory/workspace-init.py --name my-app --vision factory/active/my-app/VISION.md
    python3 factory/workspace-init.py --name my-app --blueprint factory/active/my-app/BLUEPRINT.md
"""

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path

ORG_DIR = Path(__file__).parent.parent / "org"
FACTORY_DIR = Path(__file__).parent
ROSTER_PATH = ORG_DIR / "ROSTER.md"
PROMPT_LOG = ORG_DIR / "prompts" / "prompt-audit.ndjson"

AGENT_PLATFORM_MAP = {
    "iOS": "ENG-iOS",
    "Swift": "ENG-iOS",
    "Python": "ENG-PY",
    "FastAPI": "ENG-PY",
    "CLI": "ENG-PY",
    "Infra": "ENG-INFRA",
    "Infrastructure": "ENG-INFRA",
    "Deploy": "DEVOPS-1",
    "Web": "ENG-WEB",
}


def detect_engineer(phase_title: str, deliverables: list[str]) -> str:
    text = (phase_title + " ".join(deliverables)).lower()
    if any(k in text for k in ["swift", "ios", "xcode", "swiftui"]):
        return "ENG-iOS"
    if any(k in text for k in ["deploy", "systemd", "docker", "caddy", "service"]):
        return "ENG-INFRA"
    if any(k in text for k in ["python", "fastapi", "cli", "pytest"]):
        return "ENG-PY"
    return "ENG-PY"  # default


def generate_workspace_instructions(name: str, vision_content: str, blueprint_content: str) -> str:
    return f"""# WORKSPACE — {name}
> Auto-generated by T.G.A.O.T.U. workspace-init
> Created: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}

## Purpose
{vision_content.splitlines()[0] if vision_content else '(see VISION.md)'}

## Workspace Rules

1. **Single source of truth** — BLUEPRINT.md governs. Any conflict defers to BLUEPRINT.
2. **Phase discipline** — no agent touches files outside their assigned phase deliverables.
3. **Atomic commits** — one commit per deliverable. Message = intent, not description.
4. **Validation before advance** — BUILD_STATE.md must show PASS before next phase starts.
5. **Prompt logging** — every inter-agent directive is logged to `org/prompts/prompt-audit.ndjson`.

## Active Agents for This Workspace

| Role | Agent | Phase(s) |
|------|-------|----------|
| Product Manager | PM-1 | Pre-build |
| UI Designer | DESIGN-1 | Pre-build |
| Architect | ARCH-1 | Pre-build |
| QA Engineer | QA-1 | Every phase |
| Deploy Engineer | DEVOPS-1 | Final phase |
| Tech Lead | SUP-1 | On escalation |

## File Map

```
factory/active/{name}/
├── VISION.md        — Edwin's original brief (read-only)
├── PRD.md           — Product requirements (PM-1 output)
├── UI-SPEC.md       — Interface specification (DESIGN-1 output)
├── BLUEPRINT.md     — Technical plan (ARCH-1 output)
├── BUILD_STATE.md   — Live phase tracker (updated by every agent)
├── BUILD_STATE.json — Machine-readable state
├── WORKSPACE.md     — This file
└── qa-reports/      — QA validation reports per phase
```

## How to Resume This Workspace
```bash
python3 factory/build-loop.py factory/active/{name}/
```
"""


def generate_phase_directive(phase_num: int, phase_title: str, agent_id: str,
                              deliverables: list[str], validation_cmd: str,
                              app_name: str) -> str:
    """Generate the exact directive prompt sent to an agent for a phase."""
    deliverables_list = "\n".join(f"- {d}" for d in deliverables)
    return f"""You are {agent_id}. You have one assignment.

## Assignment: Phase {phase_num} — {phase_title}
## App: {app_name}
## Blueprint: factory/active/{app_name}/BLUEPRINT.md

## Your deliverables for this phase:
{deliverables_list}

## Validation (you run this — phase is NOT done until it passes):
```
{validation_cmd}
```

## Rules:
1. Read BLUEPRINT.md Phase {phase_num} completely before writing a single line.
2. Touch only the files listed in your deliverables above.
3. Run the validation command. If it fails, self-repair up to 3 times.
4. After 3 failures, write the exact error to org/logs/supervisor.log and stop.
5. On success: update BUILD_STATE.md phase {phase_num} to ✅ complete.
6. Commit each deliverable file atomically with an intent-first message.

Begin now. No questions."""


def log_prompt(sender: str, receiver: str, purpose: str, prompt: str) -> None:
    """Append prompt to audit log in NDJSON format."""
    PROMPT_LOG.parent.mkdir(parents=True, exist_ok=True)
    entry = {
        "ts": datetime.now(timezone.utc).isoformat(),
        "sender": sender,
        "receiver": receiver,
        "purpose": purpose,
        "prompt_length": len(prompt),
        "prompt_preview": prompt[:200],
        "full_prompt_hash": str(hash(prompt)),
        "outcome": "pending",
        "effectiveness_score": None,
        "qa_notes": None
    }
    with open(PROMPT_LOG, "a") as f:
        f.write(json.dumps(entry) + "\n")


def parse_blueprint_phases(blueprint_content: str) -> list[dict]:
    """Extract phase specs from BLUEPRINT.md."""
    import re
    phases = []
    phase_blocks = re.split(r"### Phase \d+", blueprint_content)
    phase_headers = re.findall(r"### Phase (\d+) — (.+)", blueprint_content)

    for i, (num, title) in enumerate(phase_headers):
        block = phase_blocks[i + 1] if i + 1 < len(phase_blocks) else ""
        deliverables = re.findall(r"- (.+\.(?:swift|py|md|json|sh|yaml|yml))", block)
        validation = re.search(r"Command: `(.+?)`", block)
        worker = re.search(r"Worker: (.+)", block)
        phases.append({
            "number": int(num),
            "title": title.strip(),
            "deliverables": deliverables or ["(see BLUEPRINT.md)"],
            "validation": validation.group(1) if validation else "echo 'validate manually'",
            "worker": worker.group(1).strip() if worker else detect_engineer(title, deliverables),
        })
    return phases


def main():
    parser = argparse.ArgumentParser(description="Initialize a T.G.A.O.T.U. workspace")
    parser.add_argument("--name", required=True, help="App name")
    parser.add_argument("--vision", help="Path to VISION.md")
    parser.add_argument("--blueprint", help="Path to BLUEPRINT.md")
    parser.add_argument("--generate-directives", action="store_true",
                        help="Generate phase directive prompts for all agents")
    args = parser.parse_args()

    app_dir = FACTORY_DIR / "active" / args.name
    app_dir.mkdir(parents=True, exist_ok=True)

    vision_content = ""
    blueprint_content = ""

    if args.vision:
        vision_path = Path(args.vision)
        if vision_path.exists():
            vision_content = vision_path.read_text()

    if args.blueprint:
        blueprint_path = Path(args.blueprint)
        if blueprint_path.exists():
            blueprint_content = blueprint_path.read_text()

    # Write WORKSPACE.md
    workspace = generate_workspace_instructions(args.name, vision_content, blueprint_content)
    workspace_path = app_dir / "WORKSPACE.md"
    workspace_path.write_text(workspace)
    print(f"[Init] WORKSPACE.md → {workspace_path}")

    # Generate phase directives if blueprint exists
    if blueprint_content and args.generate_directives:
        phases = parse_blueprint_phases(blueprint_content)
        directives_dir = app_dir / "directives"
        directives_dir.mkdir(exist_ok=True)

        for phase in phases:
            directive = generate_phase_directive(
                phase["number"], phase["title"], phase["worker"],
                phase["deliverables"], phase["validation"], args.name
            )
            directive_path = directives_dir / f"phase-{phase['number']}-{phase['worker'].lower()}.md"
            directive_path.write_text(directive)

            # Log the prompt
            log_prompt(
                sender="Eva (COO)",
                receiver=phase["worker"],
                purpose=f"{args.name} / Phase {phase['number']} — {phase['title']}",
                prompt=directive
            )
            print(f"[Init] Directive → {directive_path} [logged to prompt audit]")

        print(f"\n[Init] {len(phases)} phase directives generated and logged.")

    print(f"\n[Init] Workspace ready: {app_dir}/")
    print(f"       WORKSPACE.md written")
    if args.generate_directives:
        print(f"       Prompts logged to: {PROMPT_LOG}")


if __name__ == "__main__":
    main()
